# Simple workflow for deploying static content to GitHub Pages
name: Copy README files to the pages branch

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths: ["README.md", "**/README.md]

jobs:
  copy:
    name: Copy my files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        
        run: |
          files=$(find **.README.md -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout pages       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "copy files"  # commit to the repository (ignore if no modification)
          git push origin pages # push to remote branch
